# Preparation of ratings and series info

data source https://www.kaggle.com/bcruise/the-office-episodes-data?select=the_office_episodes.csv

In [68]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [69]:
ep = pd.read_csv('the_office_episodes.csv')

In [70]:
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   season                 201 non-null    int64
 1   episode_num_in_season  201 non-null    int64
 2   episode_num_overall    201 non-null    int64
 3   title                  201 non-null    object
 4   directed_by            201 non-null    object
 5   written_by             201 non-null    object
 6   original_air_date      201 non-null    object
 7   prod_code              201 non-null    int64
 8   us_viewers             201 non-null    float64
dtypes: float64(1), int64(4), object(4)
memory usage: 14.3+ KB

In [71]:
ep.head(10)

,season,episode_num_in_season,episode_num_overall,title,directed_by,written_by,original_air_date,prod_code,us_viewers
0,1,1,1,Pilot,Ken Kwapis,Ricky Gervais & Stephen Merchant and Greg Daniels,2005-03-24,1001,11200000.0
1,1,2,2,Diversity Day,Ken Kwapis,B. J. Novak,2005-03-29,1002,6000000.0
2,1,3,3,Health Care,Ken Whittingham,Paul Lieberstein,2005-04-05,1006,5800000.0
3,1,4,4,The Alliance,Bryan Gordon,Michael Schur,2005-04-12,1004,5400000.0
4,1,5,5,Basketball,Greg Daniels,Greg Daniels,2005-04-19,1005,5000000.0
5,1,6,6,Hot Girl,Amy Heckerling,Mindy Kaling,2005-04-26,1003,4800000.0
6,2,1,7,The Dundies,Greg Daniels,Mindy Kaling,2005-09-20,2003,9000000.0
7,2,2,8,Sexual Harassment,Ken Kwapis,B. J. Novak,2005-09-27,2002,7130000.0
8,2,3,9,Office Olympics,Paul Feig,Michael Schur,2005-10-04,2004,8300000.0
9,2,4,10,The Fire,Ken Kwapis,B. J. Novak,2005-10-11,2001,7600000.0

In [72]:
rate = pd.read_csv('the_office_imdb.csv')

In [73]:
rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   season             188 non-null    int64
 1   episode_num        188 non-null    int64
 2   title              188 non-null    object
 3   original_air_date  188 non-null    object
 4   imdb_rating        188 non-null    float64
 5   total_votes        188 non-null    int64
 6   desc               188 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 10.4+ KB

In [74]:
rate.head()

,season,episode_num,title,original_air_date,imdb_rating,total_votes,desc
0,1,1,Pilot,2005-03-24,7.4,7006,The premiere episode introduces the boss and s...
1,1,2,Diversity Day,2005-03-29,8.3,6902,Michael's off color remark puts a sensitivity ...
2,1,3,Health Care,2005-04-05,7.7,5756,Michael leaves Dwight in charge of picking the...
3,1,4,The Alliance,2005-04-12,8.0,5579,"Just for a laugh, Jim agrees to an alliance wi..."
4,1,5,Basketball,2005-04-19,8.4,6183,Michael and his staff challenge the warehouse ...

In [75]:
def all_episodes(df):
    seasons = df.season.unique()
    
    for season in seasons:
        print()
        print(season)
        
        print(df[df.season==season].episode_num.unique())

In [76]:
all_episodes(rate)

1
[1 2 3 4 5 6]

2
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]

3
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

4
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

5
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]

6
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]

7
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

8
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

9
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

# Feature Engineering

## Mark all double series

In [77]:
doubled = ep.title.value_counts()

In [78]:
double_titles = []
for name, FT in zip(doubled.index, doubled):
    if FT==2:
        double_titles.append(name)

In [79]:
double_titles

['Money',
 'Launch Party',
 'A Benihana Christmas',
 'Search Committee',
 'Classy Christmas',
 'Goodbye, Toby',
 'Finale',
 'Fun Run',
 'Stress Relief',
 'The Job',
 'Dunder Mifflin Infinity',
 'Weight Loss',
 'A.A.R.M.']

In [80]:
rate['double'] = 0

for name in double_titles:
    rate.loc[rate.title==name,'double']=1

In [81]:
rate[rate.double==1]

,season,episode_num,title,original_air_date,imdb_rating,total_votes,desc,double
37,3,10,A Benihana Christmas,2006-12-14,8.8,4791,Trouble among the members of the party plannin...,1
50,3,23,The Job,2007-05-17,9.3,5482,"Michael appoints Dwight as regional manager, a...",1
51,4,1,Fun Run,2007-09-27,8.8,5065,Michael accidentally runs over Meridith in the...,1
52,4,2,Dunder Mifflin Infinity,2007-10-04,8.3,4174,Michael feels threatened when Ryan returns to ...,1
53,4,3,Launch Party,2007-10-11,8.4,4064,The Dunder Mifflin Infinity website is launchi...,1
54,4,4,Money,2007-10-18,8.7,4377,"As Jan renovates the condo, Michael confronts ...",1
64,4,14,"Goodbye, Toby",2008-05-15,9.4,5577,Michael throws an extravagant going-away party...,1
65,5,1,Weight Loss,2008-09-25,8.8,4597,Michael tries to motivate the Scranton branch ...,1
77,5,13,Stress Relief,2009-02-01,9.7,11895,Dwight's too-realistic fire alarm gives Stanle...,1
127,7,11,Classy Christmas,2010-12-09,9.0,4190,Michael throws an elaborate Christmas party to...,1
140,7,24,Search Committee,2011-05-19,8.7,3719,The Scranton branch puts together a search com...,1
186,9,22,A.A.R.M.,2013-05-09,9.5,5930,Dwight prepares for a marriage proposal and hi...,1
187,9,23,Finale,2013-05-16,9.8,15245,"One year later, Dunder Mifflin employees past ...",1

In [82]:
rate[rate.double==1].count()

season               13
episode_num          13
title                13
original_air_date    13
imdb_rating          13
total_votes          13
desc                 13
double               13
dtype: int64

## Renumerate all series following double series

In [83]:
rate[rate.title.str.lower().str.contains('delivery')]

,season,episode_num,title,original_air_date,imdb_rating,total_votes,desc,double
107,6,17,The Delivery: Part 1,2010-03-04,8.4,3438,Pam goes into labor and Jim is ready to take h...,0
108,6,18,The Delivery: Part 2,2010-03-04,8.5,3445,"After the baby is born, Pam has trouble gettin...",0

In [84]:
def shift_numeration(db):
    db['episode_shifted'] = db['episode_num']
    
    for season in range(1,10):
        episodes = np.sort(db[db.season==season].episode_num.unique())

        for episode in episodes: 
#             print(season, episode)
            
            if db[(db.season==season) & (db.episode_num==episode)].double.values==1:
                for following in range(episode + 1, max(episodes)+1):
                    old_val = db[(db.season==season) & (db.episode_num==following)].episode_shifted
                    db.loc[(db.season==season) & (db.episode_num==following),'episode_shifted'] = old_val + 1

    return db

In [85]:
rate_n = rate.copy(deep=True)

In [86]:
rate=shift_numeration(rate)

In [87]:
rate[rate.season==3]

,season,episode_num,title,original_air_date,imdb_rating,total_votes,desc,double,episode_shifted
28,3,1,Gay Witch Hunt,2006-09-21,9.0,5952,"Michael apologizes to Oscar, after he finds ou...",0,1
29,3,2,The Convention,2006-09-28,8.2,4354,Michael and Dwight go to a convention in Phila...,0,2
30,3,3,The Coup,2006-10-05,8.5,4562,Michael is in trouble once again as Jan busts ...,0,3
31,3,4,Grief Counseling,2006-10-12,8.0,4366,Michael takes on the role of office grief coun...,0,4
32,3,5,Initiation,2006-10-19,8.1,4248,Dwight takes former temp Ryan to his beet farm...,0,5
33,3,6,Diwali,2006-11-02,7.9,4443,Michael encourages the entire Scranton branch ...,0,6
34,3,7,Branch Closing,2006-11-09,8.6,4371,When Jan tells Michael that the Scranton Branc...,0,7
35,3,8,The Merger,2006-11-16,8.7,4558,Jan informs Michael that the Scanton branch of...,0,8
36,3,9,The Convict,2006-11-30,8.3,4564,Michael learns that one of the new employees a...,0,9
37,3,10,A Benihana Christmas,2006-12-14,8.8,4791,Trouble among the members of the party plannin...,1,10
38,3,11,Back from Vacation,2007-01-04,8.6,4333,Michael isn't supposed to let anyone know that...,0,12
39,3,12,Traveling Salesmen,2007-01-11,8.6,4371,Dwight does a favor for Angela to keep her fro...,0,13
40,3,13,The Return,2007-01-18,8.8,4592,Andy does the impossible--he makes everyone in...,0,14
41,3,14,Ben Franklin,2007-02-01,8.0,4246,Michael asks Jim to get a male stripper for Ph...,0,15
42,3,15,Phyllis' Wedding,2007-02-08,8.2,4301,Michael exaggerates the importance of his smal...,0,16
43,3,16,Business School,2007-02-15,8.9,4994,Michael is a guest speaker for Ryan's business...,0,17
44,3,17,Cocktails,2007-02-22,8.5,4251,While Michael and Jan go to their first Dunder...,0,18
45,3,18,The Negotiation,2007-04-05,9.0,4848,"Dwight saves Jim from an attack by Roy, but Dw...",0,19
46,3,19,Safety Training,2007-04-12,8.8,4516,Andy returns to the office after weeks of ange...,0,20
47,3,20,Product Recall,2007-04-26,8.7,4455,Michael tries to be proactive during a waterma...,0,21
48,3,21,Women's Appreciation,2007-05-03,8.8,4519,"Phyllis gets flashed in the parking lot, and D...",0,22
49,3,22,Beach Games,2007-05-10,9.2,5211,"Michael uses ""beach day"" at Dunder-Mifflin to ...",0,23
50,3,23,The Job,2007-05-17,9.3,5482,"Michael appoints Dwight as regional manager, a...",1,24

In [88]:
all_episodes(rate)

1
[1 2 3 4 5 6]

2
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]

3
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

4
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

5
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]

6
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]

7
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

8
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

9
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

## Delete one of  "Niagara" and one of  "The delivery" series
those two double series are not doubled in imdb for some reason. Since in schrute dataset they are double, i will merge them. Since this double series have almost the same imdb rating,the merging will not will not introduce significant inaccuracies.  and compute wieighted average imdb rating.

### niagara

In [89]:
rate[rate.title.str.lower().str.contains('niagara')]

,season,episode_num,title,original_air_date,imdb_rating,total_votes,desc,double,episode_shifted
94,6,4,Niagara: Part 1,2009-10-08,9.4,6277,The Office travels to Niagara Falls to celebra...,0,4
95,6,5,Niagara: Part 2,2009-10-08,9.5,5122,Pam is forced to deal with an embarrassing inj...,0,5

In [90]:
rates = rate[rate.title.str.lower().str.contains('niagara')].imdb_rating.values
votes = rate[rate.title.str.lower().str.contains('niagara')].total_votes.values

av = np.dot(rates, votes)/sum(votes)
print(rates, votes, round(av,1))

[9.4 9.5] [6277 5122] 9.4

In [91]:
rate.drop(rate[rate.title=='Niagara: Part 2'].index, axis=0,inplace=True)

In [92]:
rate.loc[rate.title.str.lower().str.contains('niagara'),'title'] = 'Niagara'
rate.loc[rate.title.str.lower().str.contains('niagara'),'double'] = 1

In [93]:
rate[rate.title.str.lower().str.contains('niagara')]

,season,episode_num,title,original_air_date,imdb_rating,total_votes,desc,double,episode_shifted
94,6,4,Niagara,2009-10-08,9.4,6277,The Office travels to Niagara Falls to celebra...,1,4

### delivery

In [94]:
rate[rate.title.str.lower().str.contains('delivery')]

,season,episode_num,title,original_air_date,imdb_rating,total_votes,desc,double,episode_shifted
107,6,17,The Delivery: Part 1,2010-03-04,8.4,3438,Pam goes into labor and Jim is ready to take h...,0,17
108,6,18,The Delivery: Part 2,2010-03-04,8.5,3445,"After the baby is born, Pam has trouble gettin...",0,18

In [95]:
rates = rate[rate.title.str.lower().str.contains('delivery')].imdb_rating.values
votes = rate[rate.title.str.lower().str.contains('delivery')].total_votes.values

av = np.dot(rates, votes)/sum(votes)
print(rates, votes, round(av,1))

[8.4 8.5] [3438 3445] 8.5

In [96]:
rate.drop(rate[rate.title=='The Delivery: Part 2'].index, axis=0,inplace=True)

In [97]:
rate.loc[rate.title.str.lower().str.contains('delivery'),'double'] = 1
rate.loc[rate.title.str.lower().str.contains('delivery'),'title'] = 'The Delivery'
rate.loc[rate.title.str.lower().str.contains('delivery'),'imdb_rating'] = round(av,1)

In [98]:
rate[rate.title.str.lower().str.contains('delivery')]

,season,episode_num,title,original_air_date,imdb_rating,total_votes,desc,double,episode_shifted
107,6,17,The Delivery,2010-03-04,8.5,3438,Pam goes into labor and Jim is ready to take h...,1,17

## Create month feature

In [99]:
rate['date'] = pd.to_datetime(rate['original_air_date'])

In [100]:
rate['month'] = rate['date'].apply(lambda date: date.month)

In [101]:
rate

,season,episode_num,title,original_air_date,imdb_rating,total_votes,desc,double,episode_shifted,date,month
0,1,1,Pilot,2005-03-24,7.4,7006,The premiere episode introduces the boss and s...,0,1,2005-03-24,3
1,1,2,Diversity Day,2005-03-29,8.3,6902,Michael's off color remark puts a sensitivity ...,0,2,2005-03-29,3
2,1,3,Health Care,2005-04-05,7.7,5756,Michael leaves Dwight in charge of picking the...,0,3,2005-04-05,4
3,1,4,The Alliance,2005-04-12,8.0,5579,"Just for a laugh, Jim agrees to an alliance wi...",0,4,2005-04-12,4
4,1,5,Basketball,2005-04-19,8.4,6183,Michael and his staff challenge the warehouse ...,0,5,2005-04-19,4
...,...,...,...,...,...,...,...,...,...,...,...
183,9,19,Stairmageddon,2013-04-11,8.0,2961,Dwight shoots Stanley with a bull tranquilizer...,0,19,2013-04-11,4
184,9,20,Paper Airplane,2013-04-25,8.0,3040,The employees hold a paper airplane competitio...,0,20,2013-04-25,4
185,9,21,Livin' the Dream,2013-05-02,9.1,4448,Dwight becomes regional manager after Andy qui...,0,21,2013-05-02,5
186,9,22,A.A.R.M.,2013-05-09,9.5,5930,Dwight prepares for a marriage proposal and hi...,1,22,2013-05-09,5
187,9,23,Finale,2013-05-16,9.8,15245,"One year later, Dunder Mifflin employees past ...",1,24,2013-05-16,5

# Add info from schrute dataset

In [102]:
text = pd.read_csv('schrute_episode_list.csv')

In [103]:
text.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   season    186 non-null    int64
 1   episode   186 non-null    int64
 2   title     186 non-null    object
 3   director  186 non-null    object
 4   writer    186 non-null    object
dtypes: int64(2), object(3)
memory usage: 7.4+ KB

In [104]:
text.head()

,season,episode,title,director,writer
0,1,1,Pilot,Ken Kwapis,Ricky Gervais;Stephen Merchant;Greg Daniels
1,1,2,Diversity Day,Ken Kwapis,B.J. Novak
2,1,3,Health Care,Ken Whittingham,Paul Lieberstein
3,1,4,The Alliance,Bryan Gordon,Michael Schur
4,1,5,Basketball,Greg Daniels,Greg Daniels

In [105]:
text.astype({'season':'int32','episode':'int32'}).dtypes

season       int32
episode      int32
title       object
director    object
writer      object
dtype: object

## Compare with SChrute episode list

In [106]:
count = 0
for season in range(1,10):
        episodes = np.sort(rate[rate.season==season].episode_shifted.unique())

        for episode in episodes: 
            print()
            print(season, episode)
            print(rate[(rate.season==season) & (rate.episode_shifted==episode)].title.values)
            
            if len(text[(text.season==season) & (text.episode==episode)]) > 0:
                print(text[(text.season==season) & (text.episode==episode)].title.values)
            else:
                print('---')
                count += 1
                
print(f'{count} mismatchs')

1 1
['Pilot']
['Pilot']

1 2
['Diversity Day']
['Diversity Day']

1 3
['Health Care']
['Health Care']

1 4
['The Alliance']
['The Alliance']

1 5
['Basketball']
['Basketball']

1 6
['Hot Girl']
['Hot Girl']

2 1
['The Dundies']
['The Dundies']

2 2
['Sexual Harassment']
['Sexual Harassment']

2 3
['Office Olympics']
['Office Olympics']

2 4
['The Fire']
['The Fire']

2 5
['Halloween']
['Halloween']

2 6
['The Fight']
['The Fight']

2 7
['The Client']
['The Client']

2 8
['Performance Review']
['Performance Review']

2 9
['E-Mail Surveillance']
['E-Mail Surveilance']

2 10
['Christmas Party']
['Christmas Party']

2 11
['Booze Cruise']
['Booze Cruise']

2 12
['The Injury']
['The Injury']

2 13
['The Secret']
['The Secret']

2 14
['The Carpet']
['The Carpet']

2 15
['Boys and Girls']
['Boys & Girls']

2 16
["Valentine's Day"]
["Valentine's Day"]

2 17
["Dwight's Speech"]
["Dwight's Speech"]

2 18
['Take Your Daughter to Work Day']
['Take Your Daughter to Work Day']

2 19
["Michael's Birthday"]
["Michael's Birthday"]

2 20
['Drug Testing']
['Drug Testing']

2 21
['Conflict Resolution']
['Conflict Resolution']

2 22
['Casino Night']
['Casino Night']

3 1
['Gay Witch Hunt']
['Gay Witch Hunt']

3 2
['The Convention']
['The Convention']

3 3
['The Coup']
['The Coup']

3 4
['Grief Counseling']
['Grief Counseling']

3 5
['Initiation']
['Initiation']

3 6
['Diwali']
['Diwali']

3 7
['Branch Closing']
['Branch Closing']

3 8
['The Merger']
['The Merger']

3 9
['The Convict']
['The Convict']

3 10
['A Benihana Christmas']
['A Benihana Christmas (Parts 1&2)']

3 12
['Back from Vacation']
['Back from Vacation']

3 13
['Traveling Salesmen']
['Traveling Salesmen']

3 14
['The Return']
['The Return']

3 15
['Ben Franklin']
['Ben Franklin']

3 16
["Phyllis' Wedding"]
["Phyllis' Wedding"]

3 17
['Business School']
['Business School']

3 18
['Cocktails']
['Cocktails']

3 19
['The Negotiation']
['The Negotiation']

3 20
['Safety Training']
['Safety Training']

3 21
['Product Recall']
['Product Recall']

3 22
["Women's Appreciation"]
["Women's Appreciation"]

3 23
['Beach Games']
['Beach Games']

3 24
['The Job']
['The Job (Parts 1&2)']

4 1
['Fun Run']
['Fun Run (Parts 1&2)']

4 3
['Dunder Mifflin Infinity']
['Dunder Mifflin Infinity (Parts 1&2)']

4 5
['Launch Party']
['Launch Party (Parts 1&2)']

4 7
['Money']
['Money (Parts 1&2)']

4 9
['Local Ad']
['Local Ad']

4 10
['Branch Wars']
['Branch Wars']

4 11
['Survivor Man']
['Survivor Man']

4 12
['The Deposition']
['The Deposition']

4 13
['Dinner Party']
['Dinner Party']

4 14
['Chair Model']
['Chair Model']

4 15
['Night Out']
['Night Out']

4 16
['Did I Stutter?']
['Did I Stutter?']

4 17
['Job Fair']
['Job Fair']

4 18
['Goodbye, Toby']
['Goodbye, Toby (Parts 1&2)']

5 1
['Weight Loss']
['Weight Loss (Parts 1&2)']

5 3
['Business Ethics']
['Business Ethics']

5 4
['Baby Shower']
['Baby Shower']

5 5
['Crime Aid']
['Crime Aid']

5 6
['Employee Transfer']
['Employee Transfer']

5 7
['Customer Survey']
['Customer Survey']

5 8
['Business Trip']
['Business Trip']

5 9
['Frame Toby']
['Frame Toby']

5 10
['The Surplus']
['The Surplus']

5 11
['Moroccan Christmas']
['Moroccan Christmas']

5 12
['The Duel']
['The Duel']

5 13
['Prince Family Paper']
['Prince Family Paper']

5 14
['Stress Relief']
['Stress Relief (Parts 1&2)']

5 16
['Lecture Circuit: Part 1']
['Lecture Circuit (Part 1)']

5 17
['Lecture Circuit: Part 2']
['Lecture Circuit (Part 2)']

5 18
['Blood Drive']
['Blood Drive']

5 19
['Golden Ticket']
['Golden Ticket']

5 20
['New Boss']
['New Boss']

5 21
['Two Weeks']
['Two Weeks']

5 22
['Dream Team']
['Dream Team']

5 23
['Michael Scott Paper Company']
['The Michael Scott Paper Company']

5 24
['Heavy Competition']
['Heavy Competition']

5 25
['Broke']
['Broke']

5 26
['Casual Friday']
['Casual Friday']

5 27
['Cafe Disco']
['Cafe Disco']

5 28
['Company Picnic']
['Company Picnic']

6 1
['Gossip']
['Gossip']

6 2
['The Meeting']
['The Meeting']

6 3
['The Promotion']
['The Promotion']

6 4
['Niagara']
['Niagara (Parts 1&2)']

6 6
['Mafia']
['Mafia']

6 7
['The Lover']
['The Lover']

6 8
['Koi Pond']
['Koi Pond']

6 9
['Double Date']
['Double Date']

6 10
['Murder']
['Murder']

6 11
['Shareholder Meeting']
['Shareholder Meeting']

6 12
["Scott's Tots"]
["Scott's Tots"]

6 13
['Secret Santa']
['Secret Santa']

6 14
['The Banker']
['The Banker']

6 15
['Sabre']
['Sabre']

6 16
['Manager and Salesman']
['The Manager and the Salesman']

6 17
['The Delivery']
['The Delivery (Parts 1&2)']

6 19
["St. Patrick's Day"]
["St. Patrick's Day"]

6 20
['New Leads']
['New Leads']

6 21
['Happy Hour']
['Happy Hour']

6 22
["Secretary's Day"]
["Secretary's Day"]

6 23
['Body Language']
['Body Language']

6 24
['The Cover-Up']
['The Cover']

6 25
['The Chump']
['The Chump']

6 26
['Whistleblower']
['Whistleblower']

7 1
['Nepotism']
['Nepotism']

7 2
['Counseling']
['Counseling']

7 3
["Andy's Play"]
["Andy's Play"]

7 4
['Sex Ed']
['s*x Ed']

7 5
['The Sting']
['The Sting']

7 6
['Costume Contest']
['Costume Contest']

7 7
['Christening']
['Christening']

7 8
['Viewing Party']
['Viewing Party']

7 9
['WUPHF.com']
['WUPHF.com']

7 10
['China']
['China']

7 11
['Classy Christmas']
['Classy Christmas (Parts 1&2)']

7 13
['Ultimatum']
['Ultimatum']

7 14
['The Seminar']
['The Seminar']

7 15
['The Search']
['The Search']

7 16
['PDA']
['PDA']

7 17
['Threat Level Midnight']
['Threat Level Midnight']

7 18
['Todd Packer']
['Todd Packer']

7 19
['Garage Sale']
['Garage Sale']

7 20
['Training Day']
['Training Day']

7 21
["Michael's Last Dundies"]
["Michael's Last Dundies"]

7 22
['Goodbye, Michael']
['Goodbye, Michael']

7 23
['The Inner Circle']
['The Inner Circle']

7 24
['Dwight K. Schrute, (Acting) Manager']
['Dwight K. Schrute, (Acting) Manager']

7 25
['Search Committee']
['Search Committee (Parts 1&2)']

8 1
['The List']
['The List']

8 2
['The Incentive']
['The Incentive']

8 3
['Lotto']
['Lotto']

8 4
['Garden Party']
['Garden Party']

8 5
['Spooked']
['Spooked']

8 6
['Doomsday']
['Doomsday']

8 7
["Pam's Replacement"]
["Pam's Replacement"]

8 8
['Gettysburg']
['Gettysburg']

8 9
['Mrs. California']
['Mrs. California']

8 10
['Christmas Wishes']
['Christmas Wishes']

8 11
['Trivia']
['Trivia']

8 12
['Pool Party']
['Pool Party']

8 13
['Jury Duty']
['Jury Duty']

8 14
['Special Project']
['Special Project']

8 15
['Tallahassee']
['Tallahassee']

8 16
['After Hours']
['After Hours']

8 17
['Test the Store']
['Test The Store']

8 18
['Last Day in Florida']
['Last Day In Florida']

8 19
['Get the Girl']
['Get The Girl']

8 20
['Welcome Party']
['Welcome Party']

8 21
['Angry Andy']
['Angry Andy']

8 22
['Fundraiser']
['Fundraiser']

8 23
['Turf War']
['Turf War']

8 24
['Free Family Portrait Studio']
['Free Family Portrait Studio']

9 1
['New Guys']
['The New Guys']

9 2
["Roy's Wedding"]
["Roy's Wedding"]

9 3
["Andy's Ancestry"]
["Andy's Ancestry"]

9 4
['Work Bus']
['Work Bus']

9 5
['Here Comes Treble']
['Here Comes Treble']

9 6
['The Boat']
['The Boat']

9 7
['The Whale']
['The Whale']

9 8
['The Target']
['The Target']

9 9
['Dwight Christmas']
['Dwight Christmas']

9 10
['Lice']
['Lice']

9 11
['Suit Warehouse']
['Suit Warehouse']

9 12
['Customer Loyalty']
['Customer Loyalty']

9 13
['Junior Salesman']
['Junior Salesman']

9 14
['Vandalism']
['Vandalism']

9 15
['Couples Discount']
['Couples Discount']

9 16
['Moving On']
['Moving On']

9 17
['The Farm']
['The Farm']

9 18
['Promos']
['Promos']

9 19
['Stairmageddon']
['Stairmageddon']

9 20
['Paper Airplane']
['Paper Airplane']

9 21
["Livin' the Dream"]
["Livin' the Dream"]

9 22
['A.A.R.M.']
['A.A.R.M']

9 24
['Finale']
['Finale']
0 mismatchs

## add columns to df

In [107]:
def add_columns_from_schrute(df, text):
    df['director'] = np.nan
    df['writer'] = np.nan
    
    for season in range(1,10):
            episodes = np.sort(rate[rate.season==season].episode_shifted.unique())

            for episode in episodes: 
                director = text[(text.season==season) & (text.episode==episode)].director
                writer = text[(text.season==season) & (text.episode==episode)].writer
                
#                 print(season, episode, director.values)
                
                df.loc[(df.season==season) & (df.episode_shifted==episode),'director'] = director.values
                df.loc[(df.season==season) & (df.episode_shifted==episode),'writer'] = writer.values


    return df

In [108]:
 rate[(rate.season==6) & (rate.episode_shifted==6)]

,season,episode_num,title,original_air_date,imdb_rating,total_votes,desc,double,episode_shifted,date,month
96,6,6,Mafia,2009-10-15,7.6,3582,Michael meets with an insurance salesman that ...,0,6,2009-10-15,10

In [109]:
df = rate.copy(deep=True)
df = add_columns_from_schrute(df,text)

In [110]:
df[df.writer.isna()]

Empty DataFrame
Columns: [season, episode_num, title, original_air_date, imdb_rating, total_votes, desc, double, episode_shifted, date, month, director, writer]
Index: []

In [111]:
df[df.director.isna()]

Empty DataFrame
Columns: [season, episode_num, title, original_air_date, imdb_rating, total_votes, desc, double, episode_shifted, date, month, director, writer]
Index: []

# Delete all unnecessary columns

In [112]:
df.head()

,season,episode_num,title,original_air_date,imdb_rating,total_votes,desc,double,episode_shifted,date,month,director,writer
0,1,1,Pilot,2005-03-24,7.4,7006,The premiere episode introduces the boss and s...,0,1,2005-03-24,3,Ken Kwapis,Ricky Gervais;Stephen Merchant;Greg Daniels
1,1,2,Diversity Day,2005-03-29,8.3,6902,Michael's off color remark puts a sensitivity ...,0,2,2005-03-29,3,Ken Kwapis,B.J. Novak
2,1,3,Health Care,2005-04-05,7.7,5756,Michael leaves Dwight in charge of picking the...,0,3,2005-04-05,4,Ken Whittingham,Paul Lieberstein
3,1,4,The Alliance,2005-04-12,8.0,5579,"Just for a laugh, Jim agrees to an alliance wi...",0,4,2005-04-12,4,Bryan Gordon,Michael Schur
4,1,5,Basketball,2005-04-19,8.4,6183,Michael and his staff challenge the warehouse ...,0,5,2005-04-19,4,Greg Daniels,Greg Daniels

In [113]:
df.drop(columns=['episode_num','date','original_air_date','desc'],inplace=True)

# Renaming

In [114]:
df.rename(columns={'episode_shifted':'episode','total_votes':'votes','imdb_rating':'rating'},inplace=True)

# Saving

In [115]:
df.head()

,season,title,rating,votes,double,episode,month,director,writer
0,1,Pilot,7.4,7006,0,1,3,Ken Kwapis,Ricky Gervais;Stephen Merchant;Greg Daniels
1,1,Diversity Day,8.3,6902,0,2,3,Ken Kwapis,B.J. Novak
2,1,Health Care,7.7,5756,0,3,4,Ken Whittingham,Paul Lieberstein
3,1,The Alliance,8.0,5579,0,4,4,Bryan Gordon,Michael Schur
4,1,Basketball,8.4,6183,0,5,4,Greg Daniels,Greg Daniels

In [116]:
df.to_csv('imdb.csv',index=False)